<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Caroline Birkehammar">

<title>Home Assignment SDA: Part 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="SDA Assignment 2_files/libs/clipboard/clipboard.min.js"></script>
<script src="SDA Assignment 2_files/libs/quarto-html/quarto.js"></script>
<script src="SDA Assignment 2_files/libs/quarto-html/popper.min.js"></script>
<script src="SDA Assignment 2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="SDA Assignment 2_files/libs/quarto-html/anchor.min.js"></script>
<link href="SDA Assignment 2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SDA Assignment 2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SDA Assignment 2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SDA Assignment 2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SDA Assignment 2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Home Assignment SDA: Part 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Caroline Birkehammar </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="authors" class="level2">
<h2 class="anchored" data-anchor-id="authors">Authors</h2>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 36%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th>Email</th>
<th>Personal number</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Caroline Birkehammar</td>
<td>caroline.birkehammar@gmail.com</td>
<td>19971118-5562</td>
</tr>
<tr class="even">
<td style="text-align: left;">Steven Hiram Rubio Vasquez</td>
<td>stevenrv97@gmail.com</td>
<td>19970222-8793</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pablo Paras Ochoa</td>
<td>pablo.paras.ochoa@gmail.com</td>
<td>10/08/1998</td>
</tr>
<tr class="even">
<td style="text-align: left;">Value</td>
<td>Value</td>
<td>Value</td>
</tr>
</tbody>
</table>
<section id="load-data" class="level4">
<h4 class="anchored" data-anchor-id="load-data">Load data</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"dataset01.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"test.xlsx"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>STARTING_PRICE <span class="ot">&lt;-</span> data<span class="sc">$</span>STARTING_PRICE <span class="sc">/</span> <span class="dv">1000000</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>data[<span class="fu">c</span>(<span class="st">"REGION"</span>, <span class="st">"TYPE"</span>, <span class="st">"BALCONY"</span>)] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(data[<span class="fu">c</span>(<span class="st">"REGION"</span>, <span class="st">"TYPE"</span>, <span class="st">"BALCONY"</span>)], as.factor)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(data<span class="sc">$</span>BALCONY) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="task-1" class="level1">
<h1>Task 1</h1>
<p><strong><em>Using a significance level of 1%, test the hypothesis that half of the housing units in the region have a balcony.</em></strong></p>
<section id="data-and-problem-description" class="level4">
<h4 class="anchored" data-anchor-id="data-and-problem-description">Data and problem description</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>n_balconies <span class="ot">&lt;-</span> <span class="fu">sum</span>(data<span class="sc">$</span>BALCONY <span class="sc">==</span> <span class="dv">1</span>) <span class="co"># 390</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>n           <span class="ot">&lt;-</span> <span class="fu">length</span>(data<span class="sc">$</span>BALCONY)   <span class="co"># 701</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>phat        <span class="ot">&lt;-</span> n_balconies <span class="sc">/</span> n        <span class="co"># About 0.55635</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>p0          <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>se0         <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(p0 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p0) <span class="sc">/</span> n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The observed proportion of balconies in our sample (<span class="math inline">\(\hat{p}\)</span>) is equal to <span class="math inline">\(0.55635\)</span>, but this is not enough to conclude whether or not half the housing units in the region have a balcony. What we want to know is actually how likely it is that we would observe <span class="math inline">\(\hat{p} = 0.55635\)</span> if the true value of <span class="math inline">\(p\)</span> is <span class="math inline">\(0.5\)</span>. More formally, we first assume that <span class="math inline">\(p = 0.5\)</span> (which we denote our null hypothesis <span class="math inline">\(H_{0}\)</span>) and estimate the likelihood of having observed <span class="math inline">\(\hat{p} = 0.55635\)</span> given that <span class="math inline">\(H_{0}\)</span> is true. A 1% significance level means that our test is designed so that, on average, we will incorrectly reject the null hypothesis 1% of the time. The null and alternative hypotheses are as follows: <span class="math display">\[H_{0}: p = 0.5 \qquad H_{A}: p \ne 0.5\]</span> We can assume that the distribution of <span class="math inline">\(\hat{p}\)</span> is approximately normal (since sample estimators for samples of suffiecient size are normally distributed around the real value). For the distribution, we use mean 0.5 (<span class="math inline">\(H_{0}\)</span>) and standard deviation 0.019. Formally, the distribution is as follows: <span class="math display">\[ Since \quad n\hat{p}\hat{q} = 175.25 &gt; 5, \qquad \hat{p} \sim N\left(0.5, \sqrt{\frac{0.5 \cdot 0.5}{701}}\right) = N(0.5, 0.019) \]</span></p>
</section>
<section id="using-the-formula" class="level4">
<h4 class="anchored" data-anchor-id="using-the-formula">Using the formula</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> (phat <span class="sc">-</span> p0) <span class="sc">/</span> se0</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z)))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.002847032</code></pre>
</div>
</div>
</section>
<section id="using-built-in-functions" class="level4">
<h4 class="anchored" data-anchor-id="using-built-in-functions">Using built-in functions</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>test_balcony <span class="ot">=</span> <span class="fu">prop.test</span>(n_balconies, <span class="at">n =</span> n, <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">conf.level =</span> <span class="fl">0.99</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>test_balcony<span class="sc">$</span>p.value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003218923</code></pre>
</div>
</div>
</section>
<section id="comparing-both-metods" class="level4">
<h4 class="anchored" data-anchor-id="comparing-both-metods">Comparing both metods</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">"p-value with R of: "</span>,test_balcony<span class="sc">$</span>p.value)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "p-value with R of: 0.00321892272071506"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">"p-value by hand of: "</span>,p_value)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "p-value by hand of: 0.00284703196300162"</code></pre>
</div>
</div>
</section>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion</h4>
<p>Since the p-value is less than 0.01 in both cases, the observed proportion of balconies is very unlikely under the null hypothesis, even on the 99% significance level. Therefore, we reject the null hypothesis that <span class="math inline">\(p = 0.5\)</span>.</p>
</section>
</section>
<section id="task-2" class="level1">
<h1>Task 2</h1>
<p><strong><em>Using a significance level of 5%, test the hypothesis that the expected size of the housing units in the region is 75m2.</em></strong></p>
<section id="data-and-problem-description-1" class="level4">
<h4 class="anchored" data-anchor-id="data-and-problem-description-1">Data and problem description</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>alpha   <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>mu      <span class="ot">&lt;-</span> <span class="dv">75</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>xbar    <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>AREA)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>se      <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>((data<span class="sc">$</span>AREA <span class="sc">-</span> mu)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n<span class="dv">-1</span>)) <span class="co"># Population variance unknown</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>se_xbar <span class="ot">&lt;-</span> se <span class="sc">/</span> <span class="fu">sqrt</span>(n) <span class="co"># Variance of xbar</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(AREA), <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"grey15"</span>, <span class="at">binwidth =</span> <span class="dv">4</span>) <span class="sc">+</span> <span class="co"># Not really normally distributed...</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of area in our sample"</span>) <span class="sc">+</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Area (in square meters)"</span>) <span class="sc">+</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Absolute frequency in sample"</span>) <span class="sc">+</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="SDA-Assignment-2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The distribution as shown by the histogram is not clearly normally distributed. However, the sample size is greater than 30, so we approximate the distribution of <span class="math inline">\(\bar{x}\)</span> with a normal distribution by the central limit theorem.</p>
<p>The null and alternative hypotheses are as follows: <span class="math display">\[H_{0}: \mu = 0.75 \qquad H_{A}: \mu \ne 0.75\]</span></p>
</section>
<section id="using-the-formula-1" class="level4">
<h4 class="anchored" data-anchor-id="using-the-formula-1">Using the formula</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>t_obs2  <span class="ot">&lt;-</span> (xbar <span class="sc">-</span> mu) <span class="sc">/</span> se_xbar <span class="co"># 54.47</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>p_value2 <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="at">q=</span>t_obs2,<span class="at">df=</span>n<span class="dv">-1</span>))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_value2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.004895551</code></pre>
</div>
</div>
</section>
<section id="using-built-in-functions-1" class="level4">
<h4 class="anchored" data-anchor-id="using-built-in-functions-1">Using built-in functions</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mean_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(data<span class="sc">$</span>AREA, <span class="at">mu =</span> mu, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>mean_test<span class="sc">$</span>p.value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.004656418</code></pre>
</div>
</div>
</section>
<section id="comparing-both-metods-1" class="level4">
<h4 class="anchored" data-anchor-id="comparing-both-metods-1">Comparing both metods</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">"p-value with R of: "</span>,<span class="fu">round</span>(mean_test<span class="sc">$</span>p.value,<span class="dv">3</span>))) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "p-value with R of: 0.005"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">"p-value by hand of: "</span>,<span class="fu">round</span>(p_value2,<span class="dv">3</span>))) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "p-value by hand of: 0.005"</code></pre>
</div>
</div>
</section>
<section id="conclusion-1" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-1">Conclusion</h4>
<p>The p-value is either 0.0046 or 0.0049 depending on the method, but since the level of significance is 0.05 we reject the null hypothesis. The interpretation is that the mean (or expected) area of the housing units is not 75 square meters.</p>
</section>
</section>
<section id="task-3" class="level1">
<h1>Task 3</h1>
<p><strong><em>Estimate the proportion of apartments in the region through a 90% confidence interval.</em></strong></p>
<section id="data-and-problem-description-2" class="level4">
<h4 class="anchored" data-anchor-id="data-and-problem-description-2">Data and problem description</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>phat  <span class="ot">&lt;-</span> <span class="fu">sum</span>(data<span class="sc">$</span>TYPE <span class="sc">==</span> <span class="st">"Apartment"</span>) <span class="sc">/</span> n</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>z     <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.95</span>) <span class="co"># Two-sided, so 90% ci uses z = 0.95</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>se    <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(phat<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>phat)<span class="sc">/</span>n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The 90% confidence interval for a proportion is as follows: <span class="math display">\[ \hat{p} \pm z_{0.05} \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} \]</span></p>
</section>
<section id="using-the-formula-2" class="level4">
<h4 class="anchored" data-anchor-id="using-the-formula-2">Using the formula</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>conf_int <span class="ot">&lt;-</span> <span class="fu">c</span>((phat <span class="sc">-</span> z<span class="sc">*</span>se), phat <span class="sc">+</span> z<span class="sc">*</span>se)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_int[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8169535</code></pre>
</div>
</div>
</section>
<section id="using-the-built-in-functions" class="level4">
<h4 class="anchored" data-anchor-id="using-the-built-in-functions">Using the built-in functions</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="fu">sum</span>(data<span class="sc">$</span>TYPE <span class="sc">==</span> <span class="st">"Apartment"</span>), n, <span class="at">conf.level =</span> <span class="fl">0.9</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>ci<span class="sc">$</span>conf.int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7646586 0.8164872
attr(,"conf.level")
[1] 0.9</code></pre>
</div>
</div>
</section>
<section id="comparing-both-methods" class="level4">
<h4 class="anchored" data-anchor-id="comparing-both-methods">Comparing both methods</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">"C.I. proportion of apartments with R: ["</span>,<span class="fu">round</span>(ci<span class="sc">$</span>conf.int[<span class="dv">1</span>],<span class="dv">3</span>), <span class="st">", "</span>,<span class="fu">round</span>(ci<span class="sc">$</span>conf.int[<span class="dv">2</span>],<span class="dv">3</span>),<span class="st">"]"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C.I. proportion of apartments with R: [0.765, 0.816]"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">"C.I. proportion of apartments by hand:[ "</span>,<span class="fu">round</span>(conf_int[<span class="dv">1</span>],<span class="dv">3</span>), <span class="st">", "</span>,<span class="fu">round</span>(conf_int[<span class="dv">2</span>],<span class="dv">3</span>),<span class="st">"]"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C.I. proportion of apartments by hand:[ 0.766, 0.817]"</code></pre>
</div>
</div>
</section>
<section id="conclusion-2" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-2">Conclusion</h4>
<p>The 90% confidence interval for the proportion of housing units that are apartments is about 0.76 to 0.82.</p>
</section>
</section>
<section id="task-4" class="level1">
<h1>Task 4</h1>
<p><strong><em>Estimate the expected number of rooms of the housing units in the region through a 95% confidence interval.</em></strong></p>
<section id="data-and-problem-description-3" class="level4">
<h4 class="anchored" data-anchor-id="data-and-problem-description-3">Data and problem description</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>ROOMS)  <span class="co"># About 3.15</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>se   <span class="ot">&lt;-</span> <span class="fu">sd</span>(data<span class="sc">$</span>ROOMS)    <span class="co"># About 1.59</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>t975 <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, n<span class="dv">-1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since the variance is unknown, the distribution of the expected number of rooms follow a t-distribution. The 95% confidence interval is defined as:</p>
<p><span class="math display">\[ \bar{x} \pm t_{0.025, n-1} \frac{s_x}{\sqrt{n}} \]</span></p>
</section>
<section id="using-the-formulas" class="level4">
<h4 class="anchored" data-anchor-id="using-the-formulas">Using the formulas</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>conf_int <span class="ot">&lt;-</span> <span class="fu">c</span>((xbar <span class="sc">-</span> t975 <span class="sc">*</span> se <span class="sc">/</span> <span class="fu">sqrt</span>(n)), xbar <span class="sc">+</span> t975 <span class="sc">*</span> se <span class="sc">/</span> <span class="fu">sqrt</span>(n))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.033163 3.269262</code></pre>
</div>
</div>
</section>
<section id="using-the-built-in-functions-1" class="level4">
<h4 class="anchored" data-anchor-id="using-the-built-in-functions-1">Using the built-in functions</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">t.test</span>(data<span class="sc">$</span>ROOMS, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>ci<span class="sc">$</span>conf.int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.033163 3.269262
attr(,"conf.level")
[1] 0.95</code></pre>
</div>
</div>
</section>
<section id="conclusion-3" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-3">Conclusion</h4>
<p>The confidence interval for the mean (expected) number of rooms in the region is [3.033163, 3.269262].</p>
</section>
</section>
<section id="task-5" class="level1">
<h1>Task 5</h1>
<p><strong><em>Fit a linear regression that explains STARTING_PRICE in terms of some or all of the remaining variables (REGION, TYPE, BALCONY, ROOMS and AREA). (Tips: i. Take into account that the regression is fitted with predictive purposes; ii. Make use of appropriate numerical and graphical tools; iii. Make sure that you report the estimated regression in equation form; iv. Consider transformations and interactions between variables; v. Check the model assumptions; vi. Use appropriate criteria to decide which variables should be included in the model.)</em></strong></p>
<section id="data-exploration-and-transformation" class="level4">
<h4 class="anchored" data-anchor-id="data-exploration-and-transformation">Data exploration and transformation</h4>
<p>Linear regression makes certain assumptions, one of which is a linear relationship between the independent variables and the dependent variable. Before creating and comparing different multiple regression models, we must check the linearity assumption between the starting price and the numerical independent variables (rooms and area), and conduct appropriate transformations as needed.</p>
<p>We start by checking the relationship between rooms and starting price.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(STARTING_PRICE <span class="sc">~</span> ROOMS, <span class="at">data =</span> data, <span class="at">main =</span> <span class="st">"Without transformation"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(STARTING_PRICE) <span class="sc">~</span> ROOMS, <span class="at">data =</span> data, <span class="at">main =</span> <span class="st">"Log of Starting Price"</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(STARTING_PRICE <span class="sc">~</span> <span class="fu">log</span>(ROOMS), <span class="at">data =</span> data, <span class="at">main =</span> <span class="st">"Log of Rooms"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(STARTING_PRICE) <span class="sc">~</span> <span class="fu">log</span>(ROOMS), <span class="at">data =</span> data, <span class="at">main =</span> <span class="st">"Log of Starting Price and Rooms"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="SDA-Assignment-2_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>No clear improvement by transforming (INTERPRET THIS MORE PROBABLY)</p>
<p>We follow this by checking the linearity assumption between Starting Price and Area.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(STARTING_PRICE <span class="sc">~</span> AREA, <span class="at">data =</span> data, <span class="at">main =</span> <span class="st">"Without transformation"</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(STARTING_PRICE) <span class="sc">~</span> AREA, <span class="at">data =</span> data, <span class="at">main =</span> <span class="st">"Log of Starting Price"</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(STARTING_PRICE <span class="sc">~</span> <span class="fu">log</span>(AREA), <span class="at">data =</span> data, <span class="at">main =</span> <span class="st">"Log of Area"</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(STARTING_PRICE) <span class="sc">~</span> <span class="fu">log</span>(AREA), <span class="at">data =</span> data, <span class="at">main =</span> <span class="st">"Log of Starting Price and Area"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="SDA-Assignment-2_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>While the plot without any transformations shows a quite linear relationship between the starting price and area of housing units, it also displays more heteroskedasticity for larger housing units. Taking the log of both starting price and area renders a linear and homoskedastic plot, and could be a good option for further analysis and model creation.</p>
</section>
<section id="fit-multiple-regression-model" class="level4">
<h4 class="anchored" data-anchor-id="fit-multiple-regression-model">Fit multiple regression model</h4>
<p>We create two multiple regression models: one without any log transformations, and one using the log of the starting price and the area. We start by including all interactions between the covariates, and use stepwise backwards selection to remove abundant interactions and variables.</p>
<p>Here is the model without transformations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(STARTING_PRICE <span class="sc">~</span> REGION <span class="sc">+</span> TYPE <span class="sc">+</span> BALCONY <span class="sc">+</span> ROOMS <span class="sc">+</span> AREA <span class="sc">+</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>          REGION<span class="sc">*</span>TYPE <span class="sc">+</span> REGION<span class="sc">*</span>BALCONY <span class="sc">+</span> REGION<span class="sc">*</span>ROOMS <span class="sc">+</span> REGION<span class="sc">*</span>AREA <span class="sc">+</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>          TYPE<span class="sc">*</span>BALCONY <span class="sc">+</span> TYPE<span class="sc">*</span>ROOMS <span class="sc">+</span> TYPE<span class="sc">*</span>AREA <span class="sc">+</span> </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>          BALCONY<span class="sc">*</span>ROOMS <span class="sc">+</span> BALCONY<span class="sc">*</span>AREA <span class="sc">+</span> </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>          ROOMS<span class="sc">*</span>AREA, <span class="at">data =</span> data)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>no_log_model <span class="ot">&lt;-</span> <span class="fu">step</span>(m1, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(no_log_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = STARTING_PRICE ~ REGION + TYPE + BALCONY + ROOMS + 
    AREA + REGION:TYPE + REGION:AREA + TYPE:ROOMS + TYPE:AREA, 
    data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.9773 -1.0625  0.0256  0.9168  9.3701 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 -1.420897   0.554455  -2.563  0.01060 *  
REGIONNorthwest              2.458956   0.947598   2.595  0.00967 ** 
REGIONSoutheast              1.245424   0.931261   1.337  0.18156    
REGIONStockholm              1.706318   0.584951   2.917  0.00365 ** 
REGIONWest                   0.774388   0.706154   1.097  0.27320    
TYPETerrace                  2.616140   2.663368   0.982  0.32632    
TYPEVilla                    1.519649   1.075489   1.413  0.15812    
BALCONY1                    -0.291673   0.173814  -1.678  0.09380 .  
ROOMS                       -0.596187   0.181092  -3.292  0.00105 ** 
AREA                         0.091316   0.010144   9.002  &lt; 2e-16 ***
REGIONNorthwest:TYPETerrace  0.904760   1.289551   0.702  0.48317    
REGIONSoutheast:TYPETerrace  1.412709   1.160399   1.217  0.22386    
REGIONStockholm:TYPETerrace -2.849867   0.965599  -2.951  0.00327 ** 
REGIONWest:TYPETerrace       0.791002   1.041856   0.759  0.44798    
REGIONNorthwest:TYPEVilla    0.099325   1.459590   0.068  0.94577    
REGIONSoutheast:TYPEVilla    0.882339   1.023590   0.862  0.38899    
REGIONStockholm:TYPEVilla   -2.885108   0.879207  -3.281  0.00109 ** 
REGIONWest:TYPEVilla        -0.709722   0.929726  -0.763  0.44551    
REGIONNorthwest:AREA        -0.026664   0.012845  -2.076  0.03828 *  
REGIONSoutheast:AREA        -0.028886   0.011539  -2.503  0.01254 *  
REGIONStockholm:AREA         0.008226   0.007718   1.066  0.28693    
REGIONWest:AREA             -0.025975   0.009202  -2.823  0.00490 ** 
TYPETerrace:ROOMS            0.754882   0.541815   1.393  0.16400    
TYPEVilla:ROOMS              1.139744   0.271156   4.203 2.98e-05 ***
TYPETerrace:AREA            -0.065207   0.025638  -2.543  0.01120 *  
TYPEVilla:AREA              -0.051528   0.010899  -4.728 2.76e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.905 on 675 degrees of freedom
Multiple R-squared:  0.6162,    Adjusted R-squared:  0.602 
F-statistic: 43.35 on 25 and 675 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>And here is the model using the logs of Starting Price and Area:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(STARTING_PRICE) <span class="sc">~</span> REGION <span class="sc">+</span> TYPE <span class="sc">+</span> BALCONY <span class="sc">+</span> ROOMS <span class="sc">+</span> <span class="fu">log</span>(AREA) <span class="sc">+</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>          REGION<span class="sc">*</span>TYPE <span class="sc">+</span> REGION<span class="sc">*</span>BALCONY <span class="sc">+</span> REGION<span class="sc">*</span>ROOMS <span class="sc">+</span> REGION<span class="sc">*</span><span class="fu">log</span>(AREA) <span class="sc">+</span> </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>          TYPE<span class="sc">*</span>BALCONY <span class="sc">+</span> TYPE<span class="sc">*</span>ROOMS <span class="sc">+</span> TYPE<span class="sc">*</span><span class="fu">log</span>(AREA) <span class="sc">+</span> </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>          BALCONY<span class="sc">*</span>ROOMS <span class="sc">+</span> BALCONY<span class="sc">*</span><span class="fu">log</span>(AREA) <span class="sc">+</span> </span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>          ROOMS<span class="sc">*</span><span class="fu">log</span>(AREA), <span class="at">data =</span> data)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>log_model <span class="ot">&lt;-</span> <span class="fu">step</span>(m2, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(STARTING_PRICE) ~ REGION + TYPE + BALCONY + 
    ROOMS + log(AREA) + REGION:TYPE + REGION:ROOMS + REGION:log(AREA), 
    data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.24107 -0.22755  0.01344  0.24861  0.93169 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 -1.93813    0.49592  -3.908 0.000102 ***
REGIONNorthwest              1.17211    0.92282   1.270 0.204469    
REGIONSoutheast              3.00270    1.17878   2.547 0.011077 *  
REGIONStockholm             -0.14326    0.57441  -0.249 0.803130    
REGIONWest                   0.92313    0.76985   1.199 0.230904    
TYPETerrace                 -0.07885    0.14215  -0.555 0.579300    
TYPEVilla                    0.26554    0.11937   2.225 0.026442 *  
BALCONY1                    -0.05732    0.03250  -1.764 0.078205 .  
ROOMS                        0.06146    0.04105   1.497 0.134811    
log(AREA)                    0.68630    0.13741   4.994 7.52e-07 ***
REGIONNorthwest:TYPETerrace  0.01432    0.22550   0.064 0.949375    
REGIONSoutheast:TYPETerrace  0.33760    0.21309   1.584 0.113588    
REGIONStockholm:TYPETerrace -0.42219    0.18033  -2.341 0.019514 *  
REGIONWest:TYPETerrace       0.19281    0.19277   1.000 0.317561    
REGIONNorthwest:TYPEVilla   -0.26594    0.29074  -0.915 0.360681    
REGIONSoutheast:TYPEVilla    0.25901    0.18128   1.429 0.153520    
REGIONStockholm:TYPEVilla   -0.31517    0.16432  -1.918 0.055524 .  
REGIONWest:TYPEVilla        -0.07374    0.18372  -0.401 0.688268    
REGIONNorthwest:ROOMS        0.05568    0.08797   0.633 0.526982    
REGIONSoutheast:ROOMS        0.18811    0.08790   2.140 0.032721 *  
REGIONStockholm:ROOMS       -0.06310    0.05448  -1.158 0.247194    
REGIONWest:ROOMS             0.10311    0.07016   1.470 0.142118    
REGIONNorthwest:log(AREA)   -0.26979    0.26370  -1.023 0.306634    
REGIONSoutheast:log(AREA)   -0.90153    0.32327  -2.789 0.005439 ** 
REGIONStockholm:log(AREA)    0.18733    0.16389   1.143 0.253418    
REGIONWest:log(AREA)        -0.38626    0.21601  -1.788 0.074199 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3526 on 675 degrees of freedom
Multiple R-squared:  0.6403,    Adjusted R-squared:  0.627 
F-statistic: 48.06 on 25 and 675 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="conclusion-4" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-4">Conclusion</h4>
<p>The adjusted R-squared is greater for the model using logs.</p>
</section>
</section>
<section id="task-6" class="level1">
<h1>Task 6</h1>
<p><strong><em>The dataset test.xlsx that can be found in Athena (Resources/Part 1/Assignment) contains information on the region, the type of housing unit, the presence of a balcony, the number of rooms and the area of ten housing units. Use your regression model from exercise 5 to predict the starting price of these housing units (Provide a point prediction, ˆy, and an interval prediction.)</em></strong></p>
<section id="point-prediction" class="level4">
<h4 class="anchored" data-anchor-id="point-prediction">Point prediction</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using model without log transformation</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co">#test_1 &lt;- test</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co">#pred_1 &lt;- predict(no_log_model, newdata = test_1)</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co">#test_1$STARTING_PRICE &lt;- pred_1</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="co">#head(test_1)</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Using model with log transformation</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="co">#test_2 &lt;- test</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="co">#pred_2 &lt;- predict(log_model, newdata = test_2)</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="co">#test_2$STARTING_PRICE &lt;- pred_2</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="co">#head(test_2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interval-prediction" class="level4">
<h4 class="anchored" data-anchor-id="interval-prediction">Interval prediction</h4>
</section>
<section id="conclusion-5" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-5">Conclusion</h4>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>